name: Chzzk4jDemo
main: xyz.r2turntrue.demo.ChzzkDemoPlugin
version: 1.0.0
api-version: 1.20

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.22
  - org.jetbrains.kotlin:kotlin-reflect:1.9.22
  - io.github.R2turnTrue:chzzk4j:0.0.7